version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=chester
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Reroco34
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "123456"
   
    ports:
      - "5050:80"

volumes:
  postgres_data: