version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command: -c "./entrypoint.sh && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=chester
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Reroco34
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@mail.ru
      - DJANGO_SUPERUSER_PASSWORD=Reroco34
    volumes:
      - media:/backend/app/
    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/frontend/app
      - /app/node_modules
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
      - frontend


volumes:
  postgres_data:
  volumes:
  media:
  static:

